import {
  AuditScanRecord,
  SeoIssueItem,
  SeoPageAudit,
  ImageSeoItem,
  LinkSeoItem,
  SchemaAuditItem,
  SearchConsoleMetric,
  CoreWebVitalsMetric,
  SeoSettingsConfig,
} from "./types";

export const initialMockScans: AuditScanRecord[] = [
  {
    id: "scan-latest",
    scanType: "FULL",
    status: "COMPLETED",
    startedAt: "2026-08-13T21:30:00Z",
    completedAt: "2026-08-13T21:33:42Z",
    durationSeconds: 222,
    pagesScanned: 11,
    pagesIndexable: 11,
    pagesNonIndexable: 0,
    brokenLinksCount: 0,
    criticalIssuesCount: 0,
    highIssuesCount: 1,
    mediumIssuesCount: 3,
    lowIssuesCount: 2,
    seoScore: 94,
  },
  {
    id: "scan-prev-1",
    scanType: "FULL",
    status: "COMPLETED",
    startedAt: "2026-08-06T14:00:00Z",
    completedAt: "2026-08-06T14:04:10Z",
    durationSeconds: 250,
    pagesScanned: 11,
    pagesIndexable: 11,
    pagesNonIndexable: 0,
    brokenLinksCount: 1,
    criticalIssuesCount: 1,
    highIssuesCount: 2,
    mediumIssuesCount: 4,
    lowIssuesCount: 3,
    seoScore: 87,
  },
];

export const initialMockIssues: SeoIssueItem[] = [
  {
    id: "issue-1",
    issueCode: "LONG_TITLE",
    name: "SEO Title Tag Exceeds 60 Characters",
    category: "ON_PAGE",
    severity: "MEDIUM",
    priority: "P3",
    explanation: "Title tag contains 66 characters which exceeds the recommended 60-character limit.",
    whyItMatters: "Titles longer than 60 characters risk truncated displays with ellipsis (...) on Google SERPs.",
    howToFix: "Shorten the meta title tag to 50–60 characters to ensure full visibility.",
    affectedUrls: ["/about"],
    firstDetected: "2026-08-01T10:00:00Z",
    lastDetected: "2026-08-13T21:30:00Z",
    status: "OPEN",
  },
  {
    id: "issue-2",
    issueCode: "SHORT_DESC",
    name: "Meta Description Too Short",
    category: "ON_PAGE",
    severity: "LOW",
    priority: "P4",
    explanation: "Meta description is under 120 characters long.",
    whyItMatters: "Short descriptions do not make full use of search engine snippet real estate.",
    howToFix: "Expand the description to 140–160 characters to include targeted keywords.",
    affectedUrls: ["/insights"],
    firstDetected: "2026-08-05T12:00:00Z",
    lastDetected: "2026-08-13T21:30:00Z",
    status: "OPEN",
  },
  {
    id: "issue-3",
    issueCode: "MISSING_ALT",
    name: "Image Missing ALT Attribute",
    category: "IMAGES",
    severity: "HIGH",
    priority: "P2",
    explanation: "Content images were found without descriptive ALT text.",
    whyItMatters: "ALT text enables image search indexability and satisfies accessibility requirements.",
    howToFix: "Add descriptive ALT text attributes to non-decorative image tags.",
    affectedUrls: ["/services/shopify-development"],
    firstDetected: "2026-08-08T09:00:00Z",
    lastDetected: "2026-08-13T21:30:00Z",
    status: "OPEN",
  },
];

export const initialMockPages: SeoPageAudit[] = [
  {
    id: "page-home",
    url: "https://rizwansaddique.site/",
    normalizedUrl: "https://rizwansaddique.site/",
    statusCode: 200,
    title: "Rizwan Saeed | Digital Marketing Manager & Shopify Developer",
    titleLength: 59,
    metaDescription:
      "Performance Marketer & Shopify Developer specializing in Meta Ads, Google Ads, e-commerce growth, CRO, and B2B lead generation across UAE, USA, and UK.",
    metaDescriptionLength: 153,
    canonicalUrl: "https://rizwansaddique.site/",
    h1Text: "Need More Qualified Leads, Online Sales and Measurable ROI?",
    h1Count: 1,
    headingsHierarchyValid: true,
    wordCount: 850,
    indexabilityStatus: "INDEXABLE",
    indexabilityReason: "Page is indexable.",
    noIndex: false,
    noFollow: false,
    seoScore: 98,
    internalInboundLinks: 10,
    internalOutboundLinks: 15,
    brokenLinksCount: 0,
    imagesMissingAltCount: 0,
    schemaTypes: ["Person", "WebSite"],
    ogImage: "/images/rizwan-saeed.png",
    responseTimeMs: 95,
    lastCrawledAt: "2026-08-13T21:33:00Z",
    clickDepth: 0,
  },
  {
    id: "page-about",
    url: "https://rizwansaddique.site/about",
    normalizedUrl: "https://rizwansaddique.site/about",
    statusCode: 200,
    title: "About Rizwan Saeed | Digital Marketing Manager & Shopify Developer",
    titleLength: 66,
    metaDescription:
      "Discover Rizwan Saeed's 5+ years of hands-on experience scaling performance ad campaigns, Shopify themes, CAPI tracking, and B2B lead generation across UAE, USA, and UK.",
    metaDescriptionLength: 158,
    canonicalUrl: "https://rizwansaddique.site/about",
    h1Text: "About Rizwan Saeed",
    h1Count: 1,
    headingsHierarchyValid: true,
    wordCount: 1120,
    indexabilityStatus: "INDEXABLE",
    indexabilityReason: "Page is indexable.",
    noIndex: false,
    noFollow: false,
    seoScore: 92,
    internalInboundLinks: 8,
    internalOutboundLinks: 12,
    brokenLinksCount: 0,
    imagesMissingAltCount: 0,
    schemaTypes: ["Person"],
    ogImage: "/images/rizwan-saeed.png",
    responseTimeMs: 110,
    lastCrawledAt: "2026-08-13T21:33:05Z",
    clickDepth: 1,
  },
  {
    id: "page-services",
    url: "https://rizwansaddique.site/services",
    normalizedUrl: "https://rizwansaddique.site/services",
    statusCode: 200,
    title: "Digital Growth Services — Meta Ads, Google Ads & Shopify Development",
    titleLength: 64,
    metaDescription:
      "Explore Rizwan Saeed's full range of performance marketing, e-commerce web development, SEO, and lead generation services for UAE, USA, and UK clients.",
    metaDescriptionLength: 148,
    canonicalUrl: "https://rizwansaddique.site/services",
    h1Text: "Digital Growth Services",
    h1Count: 1,
    headingsHierarchyValid: true,
    wordCount: 940,
    indexabilityStatus: "INDEXABLE",
    indexabilityReason: "Page is indexable.",
    noIndex: false,
    noFollow: false,
    seoScore: 95,
    internalInboundLinks: 9,
    internalOutboundLinks: 14,
    brokenLinksCount: 0,
    imagesMissingAltCount: 0,
    schemaTypes: ["ProfessionalService"],
    ogImage: "/images/rizwan-saeed.png",
    responseTimeMs: 105,
    lastCrawledAt: "2026-08-13T21:33:10Z",
    clickDepth: 1,
  },
  {
    id: "page-projects",
    url: "https://rizwansaddique.site/projects",
    normalizedUrl: "https://rizwansaddique.site/projects",
    statusCode: 200,
    title: "Featured Case Studies & Web Development Projects | Rizwan Saeed",
    titleLength: 61,
    metaDescription:
      "Curated portfolio of high-performing web applications, e-commerce stores, UI/UX design systems, and digital growth campaigns engineered for measurable impact.",
    metaDescriptionLength: 155,
    canonicalUrl: "https://rizwansaddique.site/projects",
    h1Text: "Featured Case Studies & Projects",
    h1Count: 1,
    headingsHierarchyValid: true,
    wordCount: 780,
    indexabilityStatus: "INDEXABLE",
    indexabilityReason: "Page is indexable.",
    noIndex: false,
    noFollow: false,
    seoScore: 94,
    internalInboundLinks: 7,
    internalOutboundLinks: 10,
    brokenLinksCount: 0,
    imagesMissingAltCount: 0,
    schemaTypes: ["WebPage"],
    ogImage: "/images/rizwan-saeed.png",
    responseTimeMs: 115,
    lastCrawledAt: "2026-08-13T21:33:15Z",
    clickDepth: 1,
  },
  {
    id: "page-results",
    url: "https://rizwansaddique.site/results",
    normalizedUrl: "https://rizwansaddique.site/results",
    statusCode: 200,
    title: "Verified Case Studies & Performance Results | Rizwan Saeed",
    titleLength: 57,
    metaDescription:
      "Review verified performance metrics: AED 4.2M+ revenue generated, AED 850K ad spend managed across UAE, USA, and UK client accounts.",
    metaDescriptionLength: 135,
    canonicalUrl: "https://rizwansaddique.site/results",
    h1Text: "Verified Case Studies & Results",
    h1Count: 1,
    headingsHierarchyValid: true,
    wordCount: 650,
    indexabilityStatus: "INDEXABLE",
    indexabilityReason: "Page is indexable.",
    noIndex: false,
    noFollow: false,
    seoScore: 96,
    internalInboundLinks: 8,
    internalOutboundLinks: 11,
    brokenLinksCount: 0,
    imagesMissingAltCount: 0,
    schemaTypes: ["ProfessionalService"],
    ogImage: "/images/rizwan-saeed.png",
    responseTimeMs: 98,
    lastCrawledAt: "2026-08-13T21:33:20Z",
    clickDepth: 1,
  },
  {
    id: "page-insights",
    url: "https://rizwansaddique.site/insights",
    normalizedUrl: "https://rizwansaddique.site/insights",
    statusCode: 200,
    title: "Digital Growth & AI Search Insights | Rizwan Saeed",
    titleLength: 51,
    metaDescription:
      "Tactical guides on performance marketing, Shopify speed optimization, Meta CAPI setup, and Generative Engine Optimization (GEO).",
    metaDescriptionLength: 125,
    canonicalUrl: "https://rizwansaddique.site/insights",
    h1Text: "Digital Growth & AI Search Insights",
    h1Count: 1,
    headingsHierarchyValid: true,
    wordCount: 920,
    indexabilityStatus: "INDEXABLE",
    indexabilityReason: "Page is indexable.",
    noIndex: false,
    noFollow: false,
    seoScore: 91,
    internalInboundLinks: 9,
    internalOutboundLinks: 13,
    brokenLinksCount: 0,
    imagesMissingAltCount: 0,
    schemaTypes: ["Article"],
    ogImage: "/images/insights/ai-search-geo.jpg",
    responseTimeMs: 125,
    lastCrawledAt: "2026-08-13T21:33:25Z",
    clickDepth: 1,
  },
  {
    id: "page-contact",
    url: "https://rizwansaddique.site/contact",
    normalizedUrl: "https://rizwansaddique.site/contact",
    statusCode: 200,
    title: "Book a Strategy Call & Contact Rizwan Saeed",
    titleLength: 43,
    metaDescription:
      "Schedule a digital marketing strategy call or request a free website & ads audit for your business in the UAE, USA, or UK.",
    metaDescriptionLength: 124,
    canonicalUrl: "https://rizwansaddique.site/contact",
    h1Text: "Book a Strategy Call",
    h1Count: 1,
    headingsHierarchyValid: true,
    wordCount: 420,
    indexabilityStatus: "INDEXABLE",
    indexabilityReason: "Page is indexable.",
    noIndex: false,
    noFollow: false,
    seoScore: 97,
    internalInboundLinks: 12,
    internalOutboundLinks: 8,
    brokenLinksCount: 0,
    imagesMissingAltCount: 0,
    schemaTypes: ["ContactPage"],
    ogImage: "/images/rizwan-saeed.png",
    responseTimeMs: 90,
    lastCrawledAt: "2026-08-13T21:33:30Z",
    clickDepth: 1,
  },
];

export const initialSearchConsoleMetrics: SearchConsoleMetric[] = [
  { query: "digital marketing manager dubai", page: "/about", clicks: 340, impressions: 4200, ctr: 8.1, position: 3.2, changePercent: 12.4 },
  { query: "shopify developer dubai", page: "/services/shopify-development", clicks: 280, impressions: 3800, ctr: 7.3, position: 2.8, changePercent: 8.5 },
  { query: "performance marketing specialist uae", page: "/services/meta-ads", clicks: 210, impressions: 2900, ctr: 7.2, position: 4.1, changePercent: -2.1 },
  { query: "generative engine optimization guide", page: "/insights/generative-engine-optimization-seo-ai-search", clicks: 195, impressions: 2100, ctr: 9.2, position: 1.9, changePercent: 24.0 },
  { query: "shopify cro speed optimization", page: "/insights/shopify-conversion-rate-optimization-speed", clicks: 160, impressions: 1850, ctr: 8.6, position: 2.3, changePercent: 15.2 },
];

export const initialCoreWebVitals: CoreWebVitalsMetric[] = [
  { url: "https://rizwansaddique.site/", device: "DESKTOP", lcpMs: 1100, inpMs: 45, cls: 0.01, fcpMs: 780, ttfbMs: 140, performanceScore: 98, status: "GOOD", lastChecked: "2026-08-13T21:30:00Z" },
  { url: "https://rizwansaddique.site/", device: "MOBILE", lcpMs: 1850, inpMs: 85, cls: 0.03, fcpMs: 1120, ttfbMs: 190, performanceScore: 92, status: "GOOD", lastChecked: "2026-08-13T21:30:00Z" },
  { url: "https://rizwansaddique.site/services", device: "DESKTOP", lcpMs: 1250, inpMs: 50, cls: 0.02, fcpMs: 820, ttfbMs: 150, performanceScore: 96, status: "GOOD", lastChecked: "2026-08-13T21:30:00Z" },
  { url: "https://rizwansaddique.site/insights", device: "DESKTOP", lcpMs: 1400, inpMs: 60, cls: 0.02, fcpMs: 910, ttfbMs: 160, performanceScore: 94, status: "GOOD", lastChecked: "2026-08-13T21:30:00Z" },
];
